
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: test-arcadedb
  labels:
    app: arcadedb
    helm.sh/chart: arcadedb-26.4.2
    app.kubernetes.io/name: arcadedb
    app.kubernetes.io/instance: test
    app.kubernetes.io/version: "26.4.2"
    app.kubernetes.io/managed-by: Helm
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: test-arcadedb
  minReplicas: 2
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
